twist_mux:
  ros__parameters:
    topics:
      zed:
        topic   : cmd_vel_zed
        timeout : 0.5
        priority: 10
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100